[project]
name = "seaglider_nortex_adcp_processing"
version = "0.0.3"
description = "Shore side processing software for the Nortek Signature 1000 ADCP system"
readme = "Readme.md"
requires-python = "==3.14.6"
dependencies = [
    # Note - these apply to the project being run stand-alone
    # When running via the Seaglider Basestation extension, the pyproject.toml for the project
    # should be used.
    "numpy==2.5.0",
    "scipy==1.18.0",
    "gsw==3.6.19",
    "netCDF4==1.7.2",
    "xarray==2026.4.0",
    "h5py==3.16.0",
    "pyproj==3.7.2",
    "cmocean==4.0.3",
    "pydantic==2.13.4",
    "PyYAML==6.0.2",
]
[project.optional-dependencies]
ci = [
    ## Testing
    "pytest==8.3.3",
    "pytest-cov==6.0.0",
    ## Linting
    "ruff==0.15.17",
    # Static Typing
    "ty==0.0.32", ## Latest    
]
dev = [
    ## Static Typing
    ## Documentation (fill in)
    "mkdocs",
    "mkdocstrings[python]",
    "mkdocs-material",
    ## Misc
    "ipython==9.14.1",
    "flynt",
]
[tool.pytest.ini_options]
pythonpath = "."
testpaths = ["tests"]

[tool.ruff]
line-length = 120
output-format = 'pylint'
include = ["./*py", "tests/*py"]
target-version = "py314"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # Numpy2.0 compat
    "NPY201",
    # Check docstrings
#    "D"
    # Annotations
    #"ANN",
]
ignore = [
  # redundant-open-modes
  "UP015",
  # outdated-version-block
  "UP036",
]
#[tool.ruff.lint.pydocstyle]
#convention = "google"
[tool.ty.src]
exclude=["BaseADCP.py","BaseADCPMission.py","DiveOcean.py","MissionOcean.py"]

[tool.coverage.html]
directory = "coverage_html_report"
[tool.coverage.run]
omit = [
    ".venv/*",
     "src/netCDF4/*",
    ]
