global_attributes:
  creator_name: "Luc Rainville"
  creator_url: "https://iop.apl.washington.edu"
  creator_email: "lucrain@uw.edu"
  institution: "Applied Physics Lab, University of Washington, Seattle, WA"
  naming_authority: "edu.washington.apl"
