global_attributes:
  time_coverage_resolution: "PT1S"
  geospatial_vertical_units: "meter"
  geospatial_vertical_resolution: "meter"
  geospatial_vertical_positive: "no"
  platform: "glider"
  geospatial_lat_units: "degrees"
  geospatial_lat_resolution: "0.0001"
  geospatial_lon_units: "degrees"
  geospatial_lon_resolution: "0.0001"
  license: "These data may be redistributed and used without restriction."
  keywords_vocabulary: "NASA/GCMD Earth Science Keywords Version 6.0.0.0"
  Metadata_Conventions: "Unidata Dataset Discovery v1.0"
  Conventions: "CF-1.6,ACDD-1.3"
  standard_name_vocabulary: "CF-1.6"
  featureType: "trajectoryProfile"
  nodc_template_version: "NODC_NetCDF_Trajectory_Template_v0.9"
  #creator_name: "Luc Rainville"
  #creator_url: "https://iop.apl.washington.edu"
  #creator_email: "lucrain@uw.edu"
  #institution: "Applied Physics Lab, University of Washington, Seattle, WA"
  #naming_authority: "edu.washington.apl"
