#
# Timeseries related
#
inverse_time:
  nc_varname: ad2cp_inv_glider_time
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Date in seconds for each solution point
    comments: Output of ad2cp inverse processing of realtime data
    units: seconds since 1970-1-1 00:00:00
    standard_name: time
    coverage_content_type: physicalMeasurement
  nc_type: d
  decimal_pts: 0
inverse_depth:
  nc_varname: ad2cp_inv_glider_depth
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Depth of the glider
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: depth
    units: m
    coverage_content_type: coordinate
  nc_type: f
  decimal_pts: 2
inverse_ocean_velocity_east:
  nc_varname: ad2cp_inv_glider_uocn
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Eastward ocean velocity at glider
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_ocean_velocity_north:
  nc_varname: ad2cp_inv_glider_vocn
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Northward ocean velocity at glider
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_ocean_velocity_vertical:
  nc_varname: ad2cp_inv_glider_wocn
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Vertical ocean velocity at glider
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
# inverse_glider_total_velocity_east:
#   nc_varname: ad2cp_inv_glider_total_east
#   nc_dimensions: ['ad2cp_inv_glider_point']
#   nc_attribs:
#     FillValue: -999
#     description: Eastward glider velocity over ground (through the water + ocean drift)
#     comments: Output of ad2cp inverse processing of realtime data
#     #standard_name: ocean speed
#     units: m s-1
#     coverage_content_type: physicalMeasurement
#   nc_type: f
#   decimal_pts: 3
# inverse_glider_total_velocity_north:
#   nc_varname: ad2cp_inv_glider_total_north
#   nc_dimensions: ['ad2cp_inv_glider_point']
#   nc_attribs:
#     FillValue: -999
#     description: Northward glider velocity over ground (through the water + ocean drift)
#     comments: Output of ad2cp inverse processing of realtime data
#     #standard_name: ocean speed
#     units: m s-1
#     coverage_content_type: physicalMeasurement
#   nc_type: f
#   decimal_pts: 3
inverse_glider_velocity_east:
  nc_varname: ad2cp_inv_glider_uttw
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Eastward glider velocity through the water
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_glider_velocity_north:
  nc_varname: ad2cp_inv_glider_vttw
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Northward glider velocity through the water
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_glider_velocity_vertical:
  nc_varname: ad2cp_inv_glider_wttw
  nc_dimensions: ['ad2cp_inv_glider_point']
  nc_attribs:
    FillValue: -999
    description: Vertical glider velocity through the water
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
#
# Timeseries - velocities in glider reference frame
#
ad2cp_frame_Ux:
  nc_varname: ad2cp_Ux
  nc_dimensions: ['ad2cp_cell_data_point', 'ad2cp_glider_data_point']
  nc_attribs:
    FillValue: -999
    description: Velocity along X-axis in glider frame coordinates
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
ad2cp_frame_Uy:
  nc_varname: ad2cp_Uy
  nc_dimensions: ['ad2cp_cell_data_point', 'ad2cp_glider_data_point']
  nc_attribs:
    FillValue: -999
    description: Velocity along Y-axis in glider frame coordinates
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
ad2cp_frame_Uz:
  nc_varname: ad2cp_Uz
  nc_dimensions: ['ad2cp_cell_data', 'ad2cp_glider_data_point']
  nc_attribs:
    FillValue: -999
    description: Velocity along Z-axis in glider frame coordinates
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
ad2cp_frame_time:
  nc_varname: ad2cp_frame_time
  nc_dimensions: ['ad2cp_cell_data', 'ad2cp_glider_data_point']
  nc_attribs:
    FillValue: -999
    description: Date in seconds for each observation
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: seconds since 1970-1-1 00:00:00
    standard_name: time
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: d
  decimal_pts: 0
#
# Timeseries - lon/lat
#
ad2cp_lonlat_time:
  nc_varname: ad2cp_lonlat_time
  nc_dimensions: ['ad2cp_lonlat_point']
  nc_attribs:
    FillValue: -999
    description: Date in seconds for each observation
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: seconds since 1970-1-1 00:00:00
    standard_name: time
    coverage_content_type: physicalMeasurement
  nc_type: d
  decimal_pts: 0
ad2cp_longitude:
  nc_varname: ad2cp_longitude
  nc_dimensions: ['ad2cp_lonlat_point']
  nc_attribs:
    FillValue: -999
    description: longitude of every sample point, from the ADCP inverse solution when underwater
    units: degrees_east
    standard_name: longitude
    long_name: estimate longitude
    coverage_content_type: coordinate
    axis: X
    valid_min: -180.0
    valid_max: 180.0
  nc_type: f
  decimal_pts: 4
ad2cp_latitude:
  nc_varname: ad2cp_latitude
  nc_dimensions: ['ad2cp_lonlat_point']
  nc_attribs:
    FillValue: -999
    description: latitude of every sample point, from the ADCP inverse solution when underwater
    standard_name: latitude
    long_name: estimated latitude
    units: degrees_north
    coverage_content_type: coordinate
    axis: Y
    valid_min: -90.0
    valid_max: 90.0
  nc_type: f
  decimal_pts: 4
  
#
# Profile related
#
inverse_profile_depth:
  nc_varname: ad2cp_inv_profile_depth
  nc_dimensions: ['ad2cp_inv_profile_point']
  nc_attribs:
    FillValue: -999
    description: Depth of the profile grid
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: depth
    units: m
    coverage_content_type: coordinate
  nc_type: f
  decimal_pts: 2
inverse_profile_velocity_east:
  nc_varname: ad2cp_inv_profile_uocn
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Eastward ocean velocity at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_profile_velocity_north:
  nc_varname: ad2cp_inv_profile_vocn
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Northward ocean velocity at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_profile_velocity_vertical:
  nc_varname: ad2cp_inv_profile_wocn
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Vertical ocean velocity at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_profile_dive:
  nc_varname: ad2cp_inv_profile_dive
  nc_dimensions: ['ad2cp_inv_profile',]
  nc_attribs:
    FillValue: -999
    description: Dive number associated with the profile
    comments: Output of ad2cp inverse processing of realtime data
    cf_role: trajectory_id
    coverage_content_type: coordinate
    units: dive number
  nc_type: i
  decimal_pts: 0
inverse_profile_longitude:
  nc_varname: ad2cp_inv_profile_longitude
  nc_dimensions: ['ad2cp_inv_profile',]
  nc_attribs:
    FillValue: -999
    description: Average longitude of the profile
    comments: Output of ad2cp inverse processing of realtime data
    units: degrees_east
    standard_name: longitude
    long_name: average longitude
    coverage_content_type: coordinate
    axis: X
  nc_type: f
  decimal_pts: 4
inverse_profile_latitude:
  nc_varname: ad2cp_inv_profile_latitude
  nc_dimensions: ['ad2cp_inv_profile',]
  nc_attribs:
    FillValue: -999
    description: Average latitude of the profile
    comments: Output of ad2cp inverse processing of realtime data
    units: degrees_east
    standard_name: latitude
    long_name: average latitude
    coverage_content_type: coordinate
    axis: Y
  nc_type: f
  decimal_pts: 4
inverse_profile_time:
  nc_varname: ad2cp_inv_profile_time
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Date in seconds for each solution point
    comments: Output of ad2cp inverse processing of realtime data
    units: seconds since 1970-1-1 00:00:00
    standard_name: time
    coverage_content_type: physicalMeasurement
  nc_type: d
  decimal_pts: 0

inverse_profile_glider_velocity_east:
  nc_varname: ad2cp_inv_profile_uttw_solution
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Eastward glider velocity through the water at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_profile_glider_velocity_north:
  nc_varname: ad2cp_inv_profile_vttw_solution
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Northward glider velocity through the water at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3
inverse_profile_glider_velocity_vertical:
  nc_varname: ad2cp_inv_profile_wttw_solution
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Vertical glider velocity through the water at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3

inverse_profile_model_velocity_east:
  nc_varname: ad2cp_inv_profile_uttw_model
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Flight model estimate of eastward glider velocity through the water at the profile depth
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: modelResult
  nc_type: f
  decimal_pts: 3
inverse_profile_model_velocity_north:
  nc_varname: ad2cp_inv_profile_vttw_model
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Flight model estimate of northward glider velocity through the water at the profile depth
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: modelResult
  nc_type: f
  decimal_pts: 3
inverse_profile_model_velocity_vertical:
  nc_varname: ad2cp_inv_profile_wttw_model
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Flight model estimate of vertical glider velocity through the water at the profile depth
    #comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: modelResult
  nc_type: f
  decimal_pts: 3

inverse_profile_velocity_error:
  nc_varname: ad2cp_inv_profile_uverr
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_attribs:
    FillValue: -999
    description: Estimate of error in model velocity at the profile depth
    comments: Output of ad2cp inverse processing of realtime data
    #standard_name: ocean speed
    units: m s-1
    coverage_content_type: physicalMeasurement
  nc_type: f
  decimal_pts: 3

profile_temperature:
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_varname: ad2cp_profile_temperature
  nc_attribs:
    FillValue: -999
    instrument: inst_ctd      
    description: corrected in-situ temperature
    units: degrees_C
    standard_name: sea_water_temperature
    long_name: CTD temperature
    coverage_content_type: physicalMeasurement
    #valid_min: -2.6
    #valid_max: 40.0
  nc_type: f
  decimal_pts: 3
profile_salinity:
  nc_dimensions: ['ad2cp_inv_profile_point', 'ad2cp_inv_profile']
  nc_varname: ad2cp_profile_salinity
  nc_attribs:
    FillValue: -999
    instrument: inst_ctd
    description: corrected salinity
    units: "1"
    standard_name: sea_water_practical_salinity
    long_name: CTD salinity
    coverage_content_type: physicalMeasurement
    l1_coords : "time lat lon z"
    #valid_min: 0.0
    #valid_max: 40.0
  nc_type: f
  decimal_pts: 3


#
# Glider CTD related
# 
glider_ctd_time:
  nc_varname: ctd_time
  nc_dimensions: ['glider_data_point']
  nc_attribs:
    FillValue: -999
    description: time for every sample point
    units: seconds since 1970-1-1T00:00:00Z
    standard_name: time
    long_name: CTD time
    coverage_content_type: physicalMeasurement
    axis: T
  nc_type: d
  decimal_pts: 0
glider_ctd_depth:
  nc_dimensions: ['glider_data_point']
  nc_varname: ctd_depth
  nc_attribs:
    FillValue: -999
    description: depth
    standard_name: depth
    long_name: CTD Depth
    units: m
    coverage_content_type: coordinate
    axis: Z
  nc_type: f
  decimal_pts: 2
glider_temperature:
  nc_dimensions: ['glider_data_point']
  nc_varname: T
  nc_attribs:
    FillValue: -999
    instrument: inst_ctd      
    description: corrected in-situ temperature
    units: degrees_C
    standard_name: sea_water_temperature
    long_name: CTD temperature
    coverage_content_type: physicalMeasurement
    valid_min: -2.6
    valid_max: 40.0
  nc_type: f
  decimal_pts: 3
glider_salinity:
  nc_dimensions: ['glider_data_point']
  nc_varname: S
  nc_attribs:
    FillValue: -999
    instrument: inst_ctd
    description: corrected salinity
    units: "1"
    standard_name: sea_water_practical_salinity
    long_name: CTD salinity
    coverage_content_type: physicalMeasurement
    l1_coords : "time lat lon z"
    valid_min: 0.0
    valid_max: 40.0
  nc_type: f
  decimal_pts: 3
glider_latitude:
  nc_dimensions: ['glider_data_point']
  nc_varname: glider_latitude
  nc_attribs:
    FillValue: -999
    description: latitude of every sample point, from the flight model when underwater
    standard_name: latitude
    long_name: estimated latitude
    units: degrees_north
    coverage_content_type: coordinate
    axis: Y
    valid_min: -90.0
    valid_max: 90.0
  nc_type: f
  decimal_pts: 4
glider_longitude:
  nc_dimensions: ['glider_data_point']
  nc_varname: glider_longitude
  nc_attribs:
    FillValue: -999
    description: longitude of every sample point, from the flight model when underwater
    units: degrees_east
    standard_name: longitude
    long_name: estimate longitude
    coverage_content_type: coordinate
    axis: X
    valid_min: -180.0
    valid_max: 180.0
  nc_type: f
  decimal_pts: 4
